"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";

import type { QuizLanguage } from "@/lib/quiz";
import type { VideoSummary } from "@/lib/types";
import { useAuth } from "./auth-context";

async function authorizedFetch(token: string, input: RequestInfo | URL, init?: RequestInit) {
  return fetch(input, { ...init, headers: { ...init?.headers, Authorization: `Bearer ${token}`, "Content-Type": "application/json" } });
}

export function QuizBuilder() {
  const { configured, token, user } = useAuth();
  const router = useRouter();
  const [url, setUrl] = useState(""); const [query, setQuery] = useState(""); const [videos, setVideos] = useState<VideoSummary[]>([]); const [selected, setSelected] = useState<VideoSummary | null>(null);
  const [age, setAge] = useState(10); const [language, setLanguage] = useState<QuizLanguage>("en"); const [count, setCount] = useState(3); const [customCount, setCustomCount] = useState(""); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(false);
  const getToken = async () => { const value = await token(); if (!value) throw new Error("Please sign in first."); return value; };
  const resolve = async () => { try { setLoading(true); const response = await authorizedFetch(await getToken(), "/api/youtube/resolve", { method: "POST", body: JSON.stringify({ url }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setSelected(data.video); setMessage(""); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to resolve video."); } finally { setLoading(false); } };
  const search = async () => { try { setLoading(true); const response = await authorizedFetch(await getToken(), `/api/youtube/search?query=${encodeURIComponent(query)}`); const data = await response.json(); if (!response.ok) throw new Error(data.error); setVideos(data.videos); setMessage(data.videos.length ? "" : "No suitable public videos found."); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to search."); } finally { setLoading(false); } };
  const create = async () => { try { if (!selected) throw new Error("Choose a video first."); const total = customCount ? Number(customCount) : count; setLoading(true); const response = await authorizedFetch(await getToken(), "/api/quizzes/generate", { method: "POST", body: JSON.stringify({ videoId: selected.id, targetAge: age, language, questionCount: total }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); router.push(`/quiz/${data.attempt.id}`); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to create quiz."); } finally { setLoading(false); } };
  return <section className="builder"><div className="input-grid"><label>YouTube URL<input value={url} onChange={(event) => setUrl(event.target.value)} placeholder="https://www.youtube.com/watch?v=..." /></label><button className="button" disabled={!configured || !user || loading} onClick={() => void resolve()}>Use URL</button></div><div className="input-grid"><label>Search YouTube<input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Try: volcanoes for kids" /></label><button className="secondary-button" disabled={!configured || !user || loading} onClick={() => void search()}>Search</button></div>{videos.length > 0 && <div className="video-list">{videos.map((video) => <button key={video.id} className={`video-card ${selected?.id === video.id ? "selected" : ""}`} onClick={() => setSelected(video)}><span>{video.title}</span><small>{video.channelTitle} · {Math.ceil(video.durationSeconds / 60)} min</small></button>)}</div>}{selected && <div className="selected-video"><strong>Selected:</strong> {selected.title}</div>}<div className="settings"><label>Target age<input type="number" min="5" max="20" value={age} onChange={(event) => setAge(Number(event.target.value))} /></label><label>Quiz language<select value={language} onChange={(event) => setLanguage(event.target.value as QuizLanguage)}><option value="en">English</option><option value="ko">한국어</option></select></label><fieldset><legend>Questions</legend>{[3, 5, 10].map((value) => <label key={value}><input type="radio" checked={count === value && !customCount} onChange={() => { setCount(value); setCustomCount(""); }} /> {value}</label>)}<label>Custom <input type="number" min="1" max="20" value={customCount} onChange={(event) => setCustomCount(event.target.value)} /></label></fieldset></div>{message && <p className="message" role="alert">{message}</p>}<button className="button primary" disabled={!configured || !user || !selected || loading} onClick={() => void create()}>{loading ? "Working…" : "Create quiz"}</button>{!configured && <p className="note">Add the Firebase and API values from `.env.example` before using live services.</p>}</section>;
}
