"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";

import type { QuizLanguage } from "@/lib/quiz";
import type { VideoSummary } from "@/lib/types";

async function postJson(input: RequestInfo | URL, body: unknown) {
  return fetch(input, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) });
}

export function QuizBuilder() {
  const router = useRouter();
  const [url, setUrl] = useState(""); const [query, setQuery] = useState(""); const [videos, setVideos] = useState<VideoSummary[]>([]); const [selected, setSelected] = useState<VideoSummary | null>(null);
  const [age, setAge] = useState(10); const [language, setLanguage] = useState<QuizLanguage>("en"); const [count, setCount] = useState(3); const [customCount, setCustomCount] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState<"resolve" | "search" | "create" | null>(null);
  const resolve = async () => { try { setBusy("resolve"); const response = await postJson("/api/youtube/resolve", { url }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setSelected(data.video); setMessage(""); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to resolve video."); } finally { setBusy(null); } };
  const search = async () => { try { setBusy("search"); const response = await fetch(`/api/youtube/search?query=${encodeURIComponent(query)}`); const data = await response.json(); if (!response.ok) throw new Error(data.error); setVideos(data.videos); setMessage(data.videos.length ? "" : "No suitable public videos found."); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to search."); } finally { setBusy(null); } };
  const create = async () => { try { if (!selected) throw new Error("Choose a video first."); const total = customCount ? Number(customCount) : count; setBusy("create"); const response = await postJson("/api/quizzes/generate", { videoId: selected.id, targetAge: age, language, questionCount: total }); const data = await response.json(); if (!response.ok) throw new Error(data.error); router.push(`/quiz/${data.attempt.id}`); } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to create quiz."); } finally { setBusy(null); } };
  return <section className="builder"><div className="input-grid"><label>YouTube URL<input value={url} onChange={(event) => setUrl(event.target.value)} placeholder="https://www.youtube.com/watch?v=..." /></label><button className="button" disabled={busy !== null} onClick={() => void resolve()}>Use URL</button></div><div className="input-grid"><label>Search YouTube<input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Try: volcanoes for kids" /></label><button className="secondary-button" disabled={busy !== null} onClick={() => void search()}>Search</button></div>{videos.length > 0 && <div className="video-list">{videos.map((video) => <button key={video.id} className={`video-card ${selected?.id === video.id ? "selected" : ""}`} onClick={() => setSelected(video)}><span>{video.title}</span><small>{video.channelTitle} · {Math.ceil(video.durationSeconds / 60)} min</small></button>)}</div>}{selected && <div className="selected-video"><strong>Selected:</strong> {selected.title}</div>}<div className="settings"><label>Target age<input type="number" min="5" max="20" value={age} onChange={(event) => setAge(Number(event.target.value))} /></label><label>Quiz language<select value={language} onChange={(event) => setLanguage(event.target.value as QuizLanguage)}><option value="en">English</option><option value="ko">한국어</option></select></label><fieldset><legend>Questions</legend>{[3, 5, 10].map((value) => <label key={value}><input type="radio" checked={count === value && !customCount} onChange={() => { setCount(value); setCustomCount(""); }} /> {value}</label>)}<label>Custom <input type="number" min="1" max="20" value={customCount} onChange={(event) => setCustomCount(event.target.value)} /></label></fieldset></div>{message && <p className="message" role="alert">{message}</p>}<button className="button primary" disabled={!selected || busy !== null} onClick={() => void create()}>{busy === "create" ? "Creating your quiz… this can take a few minutes for larger question counts" : "Create quiz"}</button></section>;
}
